name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    name: Test on Node.js ${{ matrix.node }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        node: [20, 22]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest

    - name: Install dependencies
      run: pnpm install

    - name: Lint
      run: pnpm check

    - name: Build
      run: pnpm build

    - name: Run tests
      run: pnpm coverage
